### ISSUE TITLE
Regression when calling  deleteUser

### ISSUE THREAD

**Issue by madflow** [better-auth/better-auth#3035]
### Is this suited for github?

- [x] Yes, this is suited for github

### To Reproduce

```
  session: {
    freshAge: 60 * 5,
  },
```

1. install v1.2.8 and `deleteUser` with a fresh session.

- Deletion works

2. install v1.2.9 and `deleteUser` with a fresh session.
```
{
  "code": "SESSION_EXPIRED_REAUTHENTICATE_TO_PERFORM_THIS_ACTION",
  "message": "Session expired. Re-authenticate to perform this action."
} 
```
Set freshAge to a high value.

```
  session: {
    freshAge: 60 * 5000,
  },
```

- Deletion works.

- The problem could be different timezones (or missing handling of the timezones).

### Current vs. Expected behavior

- I would expect either a documented way how to do handle different timezones or "better" handling of timezone differences (if this is even the culprit here).

### What version of Better Auth are you using?

 v1.2.9

### Provide environment information

```bash
- Next.Js 15
- Drizzle Adapter
- Postgres 17
```

### Which area(s) are affected? (Select all that apply)

Backend

### Auth config (if applicable)

```typescript

```

### Additional context

- I also tested this with this Starter: https://github.com/daveyplate/better-auth-nextjs-starter, and I get the same result:

```
services:

  # https://hub.docker.com/_/postgres/
  postgres:
    image: "postgres:17-alpine"
    command: "postgres -c log_statement=all"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
```

```
export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: "pg",
    usePlural: true,
    schema,
  }),
  user: {
    deleteUser: {
      enabled: true,
    },
  },
  emailAndPassword: {
    enabled: true,
  },
});
```

```
"use client";

import { authClient } from "@/lib/auth-client";

function handleDeleteUser() {
  authClient.deleteUser().catch(console.error);
}
export function DeleteUser() {
  return <button onClick={handleDeleteUser}>Delete user</button>;
}
```
