### ISSUE TITLE
npx @better-auth/cli generate stuck on "preparing schema..."

### ISSUE THREAD

**Issue by MrKepzie** [better-auth/better-auth#391]
**Describe the bug**

Whenever I run `npx @better-auth/cli generate`  it is stuck on "preparing schema..." forever.

**To Reproduce**

I created a mysql database using a local docker compose file:

```
services:
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: #
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: betterauth
            MYSQL_USER: #
            MYSQL_PASSWORD: #
            #MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql-storage:/var/lib/mysql'
        networks:
            - astrolocal
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p#'
            retries: 3
            timeout: 5s
    myadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOSTS=mysql
        ports:
            - "8090:80"
        depends_on:
            - mysql
        networks:
            - astrolocal
networks:
    astrolocal:
        driver: bridge
volumes:
    mysql-storage:
        driver: local
```
I then followed the documentation and created a src/auth.ts file :

```
import { betterAuth } from "better-auth";
import { createPool } from "mysql2/promise"

export const auth = betterAuth({
    database: createPool({
        host            : import.meta.env.ASTRO_DB_HOST,
        user            : import.meta.env.ASTRO_DB_USER,
        password        : import.meta.env.ASTRO_DB_PWD,
        database        : import.meta.env.ASTRO_DB_NAME
    }),
    emailAndPassword: {
		enabled: true,
	},
})
```

The environment variables are set in my `.env` file and matching what is set in the docker compose file.
Is this an issue with the mysql database ? 

Did the setup with a postgres db and everything went fine.

**Expected behavior**

The schema should be generated

**Desktop:**

- macOS, node.js 21.7.3
